### ISSUE TITLE
e2e test is broken in mac locally

### ISSUE THREAD

**Issue by katsutoxin** [lightbend/cloudstate-samples#249]
Confirmed with @srikanthops that currently running e2e test in mac is broken.
We trigger it with command `./e2e/run-tests.sh`  (due to `make run-tests` is broken now)

I think that the reason is the we do not export the port outside to kind, so browser cannot connect it.
There are two potential ways to resolve the problem 

1. expose the port in the cluster setting, we can refer the example here 
https://github.com/kubernetes-sigs/kind/pull/637#issuecomment-531433686

2. use `kubectl expose` to expose the NodePort.

Here is the error log when running `./e2e/run-tests.sh`
```+ sbt e2e/it:test
[info] Loading settings for project global-plugins from metals.sbt ...
[info] Loading global plugins from /Users/danny/.sbt/1.0/plugins
[info] Loading settings for project cloudstatemachine-build from plugins.sbt ...
[info] Loading project definition from /Users/danny/repos/cloudstatemachine/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to root (in build file:/Users/danny/repos/cloudstatemachine/)
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
11:51:13.835 [e2e-tests-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
[info] ProjectsSpec:
[info] The projects api
[info] - should allow creating a new project *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:187)
[info]   at scala.concurrent.Await$.$anonfun$ready$1(package.scala:195)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[info]   at scala.concurrent.Await$.ready(package.scala:146)
[info]   at com.lightbend.cloudstate.e2e.helpers.Driver.await(Driver.scala:18)
[info]   at com.lightbend.cloudstate.e2e.helpers.Driver.await$(Driver.scala:17)
[info]   at com.lightbend.cloudstate.e2e.ProjectsSpec.await(ProjectsSpec.scala:7)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newRawUser(DriverSpec.scala:40)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newRawUser$(DriverSpec.scala:39)
[info]   ...
[info] - should allow adding a user to a project *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:187)
[info]   at scala.concurrent.Await$.$anonfun$ready$1(package.scala:195)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[info]   at scala.concurrent.Await$.ready(package.scala:146)
[info]   at com.lightbend.cloudstate.e2e.helpers.Driver.await(Driver.scala:18)
[info]   at com.lightbend.cloudstate.e2e.helpers.Driver.await$(Driver.scala:17)
[info]   at com.lightbend.cloudstate.e2e.ProjectsSpec.await(ProjectsSpec.scala:7)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newRawUser(DriverSpec.scala:40)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newRawUser$(DriverSpec.scala:39)
[info]   ...
[info] - should not allow an unauthorized user to add another user to a project *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:187)
[info]   at scala.concurrent.Await$.$anonfun$ready$1(package.scala:195)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[info]   at scala.concurrent.Await$.ready(package.scala:146)
[info]   at com.lightbend.cloudstate.e2e.helpers.Driver.await(Driver.scala:18)
[info]   at com.lightbend.cloudstate.e2e.helpers.Driver.await$(Driver.scala:17)
[info]   at com.lightbend.cloudstate.e2e.ProjectsSpec.await(ProjectsSpec.scala:7)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newRawUser(DriverSpec.scala:40)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newRawUser$(DriverSpec.scala:39)
[info]   ...
[info] - should allow removing a user from a project *** FAILED ***
[info]   io.grpc.StatusException: UNAVAILABLE: io exception
[info]   at com.lightbend.cloudstate.e2e.helpers.Driver.await(Driver.scala:23)
[info]   at com.lightbend.cloudstate.e2e.helpers.Driver.await$(Driver.scala:17)
[info]   at com.lightbend.cloudstate.e2e.ProjectsSpec.await(ProjectsSpec.scala:7)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newRawUser(DriverSpec.scala:40)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newRawUser$(DriverSpec.scala:39)
[info]   at com.lightbend.cloudstate.e2e.ProjectsSpec.newRawUser(ProjectsSpec.scala:7)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newUser(DriverSpec.scala:36)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newUser$(DriverSpec.scala:34)
[info]   at com.lightbend.cloudstate.e2e.ProjectsSpec.newUser(ProjectsSpec.scala:7)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newCliUser(DriverSpec.scala:52)
[info]   ...
[info]   Cause: io.grpc.netty.shaded.io.netty.channel.ConnectTimeoutException: connection timed out: /172.17.0.2:32212
[info]   at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
[info]   at io.grpc.netty.shaded.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
[info]   at io.grpc.netty.shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
[info]   at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[info]   at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
[info]   at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[info]   at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
[info]   at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[info]   at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[info]   at java.base/java.lang.Thread.run(Thread.java:834)
[info]   ...
Reporter completed abruptly with an exception after receiving event: TestFailed(Ordinal(0, 10),UNAVAILABLE: io exception,ProjectsSpec,com.lightbend.cloudstate.e2e.ProjectsSpec,Some(com.lightbend.cloudstate.e2e.ProjectsSpec),The projects api should allow removing a user from a project,allow removing a user from a project,Vector(),Some(io.grpc.StatusException: UNAVAILABLE: io exception),Some(346),Some(IndentedText(- should allow removing a user from a project,should allow removing a user from a project,1)),Some(SeeStackDepthException),Some(com.lightbend.cloudstate.e2e.ProjectsSpec),None,pool-1-thread-1-ScalaTest-running-ProjectsSpec,1588359104908).
java.io.NotSerializableException: io.grpc.Status
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at org.scalatest.tools.SocketReporter.apply(SocketReporter.scala:31)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-15" java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: io.grpc.Status
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1598)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:818)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:807)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.NotSerializableException: io.grpc.Status
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at org.scalatest.tools.SocketReporter.apply(SocketReporter.scala:31)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	... 1 more
Reporter completed abruptly with an exception after receiving event: TestFailed(Ordinal(0, 12),Futures timed out after [10 seconds],ProjectsSpec,com.lightbend.cloudstate.e2e.ProjectsSpec,Some(com.lightbend.cloudstate.e2e.ProjectsSpec),The projects api should allow listing all roles of a project,allow listing all roles of a project,Vector(),Some(java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]),Some(10005),Some(IndentedText(- should allow listing all roles of a project,should allow listing all roles of a project,1)),Some(SeeStackDepthException),Some(com.lightbend.cloudstate.e2e.ProjectsSpec),None,pool-1-thread-1-ScalaTest-running-ProjectsSpec,1588359114920).
[info] - should allow listing all roles of a project *** FAILED ***
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1883)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1792)
	at java.base/java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1287)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at java.base/java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1232)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1428)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1583)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:352)
	at org.scalatest.tools.SocketReporter.apply(SocketReporter.scala:31)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.base/java.lang.Thread.run(Thread.java:834)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:187)
[info]   at scala.concurrent.Await$.$anonfun$ready$1(package.scala:195)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[info]   at scala.concurrent.Await$.ready(package.scala:146)
Reporter completed abruptly with an exception after receiving event: TestStarting(Ordinal(0, 13),ProjectsSpec,com.lightbend.cloudstate.e2e.ProjectsSpec,Some(com.lightbend.cloudstate.e2e.ProjectsSpec),The projects api should allow logging in to a project with kubectl,allow logging in to a project with kubectl,Some(MotionToSuppress),Some(LineInFile(60,ProjectsSpec.scala,Some(Please set the environment variable SCALACTIC_FILL_FILE_PATHNAMES to yes at compile time to enable this feature.))),Some(com.lightbend.cloudstate.e2e.ProjectsSpec),None,pool-1-thread-1-ScalaTest-running-ProjectsSpec,1588359114923).
[info]   at com.lightbend.cloudstate.e2e.helpers.Driver.await(Driver.scala:18)
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1883)
[info]   at com.lightbend.cloudstate.e2e.helpers.Driver.await$(Driver.scala:17)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1792)
	at java.base/java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1287)
	at java.base/java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1232)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1428)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
[info]   at com.lightbend.cloudstate.e2e.ProjectsSpec.await(ProjectsSpec.scala:7)
	at java.base/java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1583)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:352)
	at org.scalatest.tools.SocketReporter.apply(SocketReporter.scala:31)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newRawUser(DriverSpec.scala:40)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.base/java.lang.Thread.run(Thread.java:834)
[info]   at com.lightbend.cloudstate.e2e.helpers.DriverSpec.newRawUser$(DriverSpec.scala:39)
[info]   ...
Reporter completed abruptly with an exception after receiving event: TestFailed(Ordinal(0, 14),Futures timed out after [10 seconds],ProjectsSpec,com.lightbend.cloudstate.e2e.ProjectsSpec,Some(com.lightbend.cloudstate.e2e.ProjectsSpec),The projects api should allow logging in to a project with kubectl,allow logging in to a project with kubectl,Vector(),Some(java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]),Some(10006),Some(IndentedText(- should allow logging in to a project with kubectl,should allow logging in to a project with kubectl,1)),Some(SeeStackDepthException),Some(com.lightbend.cloudstate.e2e.ProjectsSpec),None,pool-1-thread-1-ScalaTest-running-ProjectsSpec,1588359124928).
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1883)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.writeByte(ObjectOutputStream.java:1921)
	at java.base/java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1582)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:352)
	at org.scalatest.tools.SocketReporter.apply(SocketReporter.scala:31)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.base/java.lang.Thread.run(Thread.java:834)
...
```

**Comment by katsutoxin** [comment]
I traced the code a little bit, and I have some founding to support my above assumption

1,   In the e2e code, it connect through a chrome docker image  https://github.com/lightbend/cloudstatemachine/blob/master/e2e/src/it/scala/com/lightbend/cloudstate/e2e/helpers/ChromeBrowser.scala#L24
    val rc = Process("docker run --rm --name chrome -d -p 4444:4444 --shm-size 2g selenium/standalone-chrome").
2. in the scala code, it connects to MANAGEMENT_HOST  , it is the  environment variable, generated from run-tests.sh.    The value is 172.17.0.2:30451 for me.
3. If I run the command kubectl get node -o wide, I can know that 172.17.0.2 is the "INTERNAL-IP" for "kind-control-plane"
4. If I run the command kubectl get service management-api -o yaml , I can know that 30451 is the node port of "management-api"

Based on above founding, if we can expose port from k8s , we can easily change environment variable "MANAGEMENT_HOST",  and run "sbt e2e/it:test" to run e2e test in mac. Note: when we run `csctl auth login`, it will talk to MANAGEMENT_HOST and get the link for UI, we need to make sure UI link also can connect :)

**Comment by katsutoxin** [comment]
some updates:  I tried some workaround, like using https://github.com/kubernetes-sigs/kind/pull/637#issuecomment-531433686 to expose the management-api port to localhost:30090,  then several e2e tests passed !  

Just to be clear, all tests involves "csctl" passed. However, the test involved "kubectl" all failed due to "cloudstate-proxy" hardcode in kubectl **context**. 

BTW, only Mac and Windows will have this problem, Linux is good. I saw several github issue mentioned that it is the mac/windows only problem.  The reason is that docker network bridge mode works different in linux and mac/windows

Here are the github issue links
https://github.com/kubernetes-sigs/kind/issues/808#issuecomment-524461274
https://github.com/kubernetes-sigs/kind/issues/99#issuecomment-458312217
https://github.com/kubernetes-sigs/kind/issues/99#issuecomment-580623207
